import { z } from 'zod';
export const SuratFormInputSchema = z.object({
  Nomor_SP3: z.string().min(1, 'Nomor SP3 harus diisi!'),
  Jenis_Tender_UP: z.string().min(1, 'Jenis Tender UP harus diisi!'),
 //Pekerjaan_UP: z.string().min(1, 'Pekerjaan UP harus diisi!'),
  Tanggal_Email: z.string().min(1, 'Tanggal Email harus diisi!'),
  Jenis_Tender: z.string().min(1, 'Jenis Tender harus diisi!'),
  Pekerjaan: z.string().min(1, 'Pekerjaan harus diisi!'),
  Perusahaan_P2: z.string().min(1, 'Perusahaan P2 harus diisi!'),
  Alamat_P2: z.string().min(1, 'Alamat P2 harus diisi!'),
  NPWP_P2: z.string().min(1, 'NPWP P2 harus diisi!'),
  Biaya_Pekerjaan: z.number().min(0, 'Biaya Pekerjaan harus diisi!'),
  terbilang_1: z.string().min(1, 'Terbilang Biaya Pekerjaanharus diisi!'),
  Jangka_Waktu_Pelaksanaan: z.number().min(0, 'Jangka Waktu Pelaksanaan harus diisi!'),
  terbilang_2: z.string().min(1, 'Terbilang Jangka Waktu Pelaksanaan harus diisi!'),
  Jangka_Waktu_Pemeliharaan: z.number().min(0, 'Jangka Waktu Pemeliharaan harus diisi!'),
  terbilang_3: z.string().min(1, 'Terbilang Jangka Waktu Pemeliharaan harus diisi!'),
  TKDN: z.number().min(0, 'TKDN harus diisi!'),
  Terbilang_TKDN: z.string().min(1, 'Terbilang TKDN harus diisi!d'),
  Tanggal_Penetapan: z.string().min(1, 'Tanggal Penetapan harus diisi!'),
  Perdir_PBJ: z.string().min(1, 'Perdir PBJ harus diisi!'),
  Nomor_Nodin: z.string().min(1, 'Nomor Nodin harus diisi!'),
  Tanggal_Nodin: z.string().min(1, 'Tanggal Nodin harus diisi!'),
});
