import { z } from 'zod';

export const SuratFormInputSchema = z.object({
  Jenis_Tender: z.string().min(1, 'Jenis Tender harus diisi!'),
  Jenis_Pengadaan: z.string().min(1, 'Jenis Pengadaan harus diisi!'),
  Jenis_Kontrak: z.string().min(1, 'Jenis Kontrak harus diisi!'),
  Pekerjaan: z.string().min(1, 'Pekerjaan harus diisi!'),
  Pekerjaan_UP: z.string().min(1, 'Pekerjaan UP harus diisi!'),
  Perdir_PBJ: z.string().min(1, 'Perdir PBJ harus diisi!'),
  Tempat_Tanda_Tangan: z.string().min(1, 'Tempat Tanda Tangan harus diisi!'),
  Tahun: z.string().min(1, 'Tahun harus diisi!'),
  Nama_P1: z.string().min(1, 'Nama P1 harus diisi!'),
  Jabatan_P1: z.string().min(1, 'Jabatan P1 harus diisi!'),
  Perusahaan_P1: z.string().min(1, 'Perusahaan P1 harus diisi!'),
  Reg_P1: z.string().min(1, 'Reg P1 harus diisi!'),
  Alamat_P1: z.string().min(1, 'Alamat P1 harus diisi!'),
  SK_P1: z.string().min(1, 'SK P1 harus diisi!'),
  No_Telp_P1: z.string().min(1, 'No Telp P1 harus diisi!'),
  Website_P1: z.string().min(1, 'Website P1 harus diisi!'),
  Faksimili_P1: z.string().min(1, 'Faksimili P1 harus diisi!'),
  Email_P1: z.string().min(1, 'Email P1 harus diisi!'),
  Jabatan_Pengawas_P1: z.string().min(1, 'Jabatan Pengawas P1 harus diisi!'),
  Sub_Reg_Pengawas_P1: z.string().min(1, 'Sub Reg Pengawas P1 harus diisi!'),
  Masa_Pemeliharaan: z.number().min(0, 'Masa Pemeliharaan harus diisi!'),
  Jaminan_Pelaksanaan: z.number().min(0, 'Jaminan Pelaksanaan harus diisi!'),
  Tempat_Pelaksanaan_Pekerjaan: z.string().min(1, 'Tempat Pelaksanaan Pekerjaan harus diisi!'),
  Pengadilan: z.string().min(1, 'Pengadilan harus diisi!'),
  Tempat_Serah_Terima: z.string().min(1, 'Tempat Serah Terima harus di isi!'),
  Persentase_Pembayaran: z.number().min(0, 'Presentase harus diisi!'),
  Nama_P2: z.string().min(1, 'Nama P2 harus diisi!'),
  Jabatan_P2: z.string().min(1, 'Jabatan P2 harus diisi!'),
  Bentuk_Perusahaan_P2: z.string().min(1, 'Bentuk Perusahaan P2 harus diisi!'),
  Perusahaan_P2: z.string().min(1, 'Perusahaan P2 harus diisi!'),
  Alamat_P2: z.string().min(1, 'Alamat P2 harus diisi!'),
  Telepon_P2: z.string().min(1, 'Telepon P2 harus diisi!'),
  Website_P2: z.string().min(1, 'Website P2 harus diisi!'),
  Faksimili_P2: z.string().min(1, 'Faksimili P2 harus diisi!'),
  Email_P2: z.string().min(1, 'Email P2 harus diisi!'),
  No_Akta_1: z.string().min(1, 'No Akta 1 harus diisi!'),
  Tanggal_Akta_1: z.string().min(1, 'Tanggal Akta 1 harus diisi!'),
  Notaris_Akta_1: z.string().min(1, 'Notaris Akta 1 harus diisi!'),
  Kota_Akta_1: z.string().min(1, 'Kota Akta 1 harus diisi!'),
  No_Pengesahan_Akta_1: z.string().min(1, 'No Pengesahan Akta 1 harus diisi!'),
  Tanggal_Pengesahan_Akta_1: z.string().min(1, 'Tanggal Pengesahan Akta 1 harus diisi!'),
  No_Akta_2: z.string().min(1, 'No Akta 2 harus diisi!'),
  Perihal_Akta_2: z.string().min(1, 'Perihal Akta 2 harus diisi!'),
  Tanggal_Akta_2: z.string().min(1, 'Tanggal Akta 2 harus diisi!'),
  Notaris_Akta_2: z.string().min(1, 'Notaris Akta 2 harus diisi!'),
  Kota_Akta_2: z.string().min(1, 'Kota Akta 2 harus diisi!'),
  Perihal_Pengesahan_Akta_2: z.string().min(1, 'Perihal Pengesahan Akta 2 harus diisi!'),
  No_Pengesahan_Akta_2: z.string().min(1, 'No Pengesahan Akta 2 harus diisi!'),
  Tanggal_Pengesahan_Akta_2: z.string().min(1, 'Tanggal Pengesahan Akta 2 harus diisi!'),
  Nomor_Rekening_P2: z.string().min(1, 'Nomor Rekening P2 harus diisi!'),
  Atas_Nama_Norek: z.string().min(1, 'Atas Nama Norek harus diisi!'),
  Nama_Bank: z.string().min(1, 'Nama Bank harus diisi!'),
  Nomor_SP3: z.string().min(1, 'Nomor SP3 harus diisi!'),
  Tanggal_SP3: z.string().min(1, 'Tanggal SP3 harus diisi!'),
  Biaya_Pekerjaan: z.number().min(0, 'Biaya Pekerjaan harus diisi!'),
  Jangka_Waktu_Pekerjaan: z.number().min(0, 'Jangka Waktu Pekerjaan harus diisi!'),
  Nilai_TKDN: z.number().min(0, 'Nilai TKDN harus diisi!'),
  Nomor_Nodin: z.string().min(1, 'Nomor Nodin harus diisi!'),
  Tanggal_Nodin: z.string().min(1, 'Tanggal Nodin harus diisi!'),
  Tanggal_Email: z.string().min(1, 'Tanggal Email harus diisi!'),
  No_BA_Rapat: z.string().min(1, 'No BA Rapat harus diisi!'),
  Tanggal_BA_Rapat: z.string().min(1, 'Tanggal BA Rapat harus diisi!'),
  No_Supen: z.string().min(1, 'No Supen harus diisi!'),
  Tanggal_Supen: z.string().min(1, 'Tanggal Supen harus diisi!'),
  Nomor_BA_Pembukaan_Penawaran: z.string().min(1, 'Nomor BA Pembukaan Penawaran harus diisi!'),
  Tanggal_BA_Pembukaan_Penawaran: z.string().min(1, 'Tanggal BA Pembukaan Penawaran harus diisi!'),
  Nomor_BA_Eval: z.string().min(1, 'Nomor BA Eval harus diisi!'),
  Tanggal_BA_Eval: z.string().min(1, 'Tanggal BA Eval harus diisi!'),
  Nomor_BA_Nego: z.string().min(1, 'Nomor BA Nego harus diisi!'),
  Tanggal_BA_Nego: z.string().min(1, 'Tanggal BA Nego harus diisi!'),
  Nomor_Pengumuman: z.string().min(1, 'Nomor Pengumuman harus diisi!'),
  Tanggal_Pengumuman: z.string().min(1, 'Tanggal Pengumuman harus diisi!'),
  terbilang_masa_pemeliharaan: z.string().min(1, 'Terbilang Masa Pemeliharaan harus diisi!'),
  terbilang_jpelaksanaan: z.string().min(1, 'Terbilang Jangka Pelaksanaan harus diisi!'),
  terbilang_biaya_pekerjaan: z.string().min(1, 'Terbilang Biaya Pekerjaan harus diisi!'),
  terbilang_jwaktu_pekerjaan: z.string().min(1, 'Terbilang Jangka Waktu Pekerjaan harus diisi!'),
  terbilang_nilai_tkdn: z.string().min(1, 'Terbilang Nilai TKDN harus diisi!'),
  Nomor_Jampel: z.string().min(1, 'Nomor Jampel harus diisi!'),
  Tanggal_Jampel: z.string().min(1, 'Tanggal Jampel harus diisi!'),
  berlaku_jampel: z.string().min(1, 'Berlaku Jampel harus diisi!'),
  berakhir_jampel: z.string().min(1, 'Berakhir Jampel harus diisi!'),
  Bank_BUMN: z.string().min(1, 'Bank BUMN harus diisi!'),
  Nomor_BA_Klarif: z.string().min(1, 'Nomor BA Klarifikasi harus diisi!'),
  Tanggal_BA_Klarif: z.string().min(1, 'Tanggal BA Klarifikasi harus diisi!'),
});